apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/wave: "-2" 
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: user
