apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  annotations:
    argocd.argoproj.io/wave: "-2"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /data/mysql
