apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/wave: "-2"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /data/mysql
