apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  annotations:
    argocd.argoproj.io/wave: "-2" 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  
    path: /data/mysql
