apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
  annotations:
    #argocd.argoproj.io/wave: "-2"
    argocd.argoproj.io/hook: PreSync
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk 
  MYSQL_PASSWORD: eW91cl9wYXNzd29yZA==  
