apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: cms
spec:
  replicas: {{ .Values.home.replicas }}
  selector:
    matchLabels:
      app: cms
      name: home-pod  
  template:
    metadata:
      name: home-pod
      labels:
        app: cms
        name: home-pod
    spec:
      containers:
      - name: cms-home
        image: "{{ .Values.home.image.name }}:{{ .Values.home.image.tag }}"
        ports:
        - containerPort: 80
