apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: {{ .Values.namespace }}
  labels:
    app: home
spec:
  selector:
    app: cms
    name: home-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
