apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cms
    name: home-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
